<template>
  <!-- Generated by Pixelmator Pro 3.7.1 -->
  <svg
    width="1024"
    height="1024"
    viewBox="0 0 1024 1024"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      id="Path"
      fill="none"
      stroke="currentColor"
      class="loader-path"
      stroke-width="70"
      stroke-linecap="round"
      pathLength="1"
      d="M 869.208252 389.934021 C 869.208252 389.934021 602.895569 599.331665 358.424561 614.764282 C 243.266891 622.033813 167.954803 625.317871 141.589981 701.883789 C 120.598915 762.843872 149.462463 824.624756 208.668823 858.986938 C 261.127625 889.432983 322.405792 861.578979 357.212463 811.50415 C 478.491089 637.026123 376.293182 336.67218 345.648895 176.770996 C 344.884064 172.779968 356.015778 169.967041 357.462982 173.76416 C 440.640503 392.001648 557.605713 636.008301 679.612488 732.351929 C 712.11322 758.016479 741.282898 769.929443 781.624939 760.576416 C 841.135315 746.779297 886.499756 659.375854 886.499756 659.375854"
    />
  </svg>
</template>

<style scoped lang="sass">
  .loader-path
    stroke-dasharray: 1
    stroke-dashoffset: 1
    animation: draw 2.2s ease-in-out infinite

  @keyframes draw
    0%
      stroke-dashoffset: 1

    50%
      stroke-dashoffset: 0

    95%
      stroke-dashoffset: -1

    100%
      stroke-dashoffset: -1
</style>
